export const pageGroupList = [
  {
    title: '工作台',
    name: 'workbench',
    components: [{ name: 'myFeaturedApplications', title: '已购特色应用' }],
  },
  { title: '应用后台', name: 'applicationBackend', components: [{ name: 'addOrUpdate', title: '编辑' }] },
  { title: 'Banner配置', name: 'bannerConfiguration', components: [{ name: 'addOrUpdate', title: '编辑' }] },
  { title: '快讯中心', name: 'newsCenter', components: [{ name: 'addOrUpdate', title: '编辑' }] },
  { title: '消息中心', name: 'messageCenter', components: [{ name: 'addOrUpdate', title: '编辑' }] },
  { title: '公告中心', name: 'announcementCenter', components: [{ name: 'addOrUpdate', title: '编辑' }] },
  { title: '应用中心', name: 'applicationCenter', components: [{ name: 'addOrUpdate', title: '编辑' }] },
  {
    title: '系统管理',
    name: 'system',
    pages: [
      { title: '租户管理', name: 'tenant', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '用户管理', name: 'user', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '公众端用户管理', name: 'publicEndUser', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '公众端街道用户管理', name: 'publicEndStreetUser', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '角色管理', name: 'role', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '菜单管理', name: 'menu', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '部门管理', name: 'department', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '岗位管理', name: 'job', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '字典管理', name: 'dictionary', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '参数设置', name: 'parameterSettings', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '通知公告', name: 'noticeAnnouncement', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '日志管理', name: 'log', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '街道子账户角色管理', name: 'streetSubAccountRole', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '街道子账户账号管理', name: 'sonTenantAccount', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '社区管理', name: 'community', components: [{ name: 'addOrUpdate', title: '编辑' }] },
    ],
  },
  {
    title: '系统监控',
    name: 'monitor',
    pages: [
      { title: '在线用户', name: 'onlineUsers', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '定时任务', name: 'scheduledTasks', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '数据监控', name: 'dataMonitoring', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '服务监控', name: 'serviceMonitoring', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '缓存监控', name: 'cacheMonitoring', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '缓存列表', name: 'cacheList', components: [{ name: 'addOrUpdate', title: '编辑' }] },
    ],
  },
  {
    title: '系统工具',
    name: 'tool',
    pages: [
      { title: '表单构建', name: 'formConstruction', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '代码生成', name: 'codeGeneration', components: [{ name: 'addOrUpdate', title: '编辑' }] },
      { title: '系统接口', name: 'systemInterface', components: [{ name: 'addOrUpdate', title: '编辑' }] },
    ],
  },
];
