export const pageGroupList = [
  {
    title: '工作台',
    name: 'workbench',
    components: [{ name: 'my-featured-applications', title: '已购特色应用' }],
  },
  { title: '应用后台', name: 'application-backend', components: [{ name: 'add-or-update', title: '编辑' }] },
  { title: 'Banner配置', name: 'banner-configuration', components: [{ name: 'add-or-update', title: '编辑' }] },
  { title: '快讯中心', name: 'news-center', components: [{ name: 'add-or-update', title: '编辑' }] },
  { title: '消息中心', name: 'message-center', components: [{ name: 'add-or-update', title: '编辑' }] },
  { title: '公告中心', name: 'announcement-center', components: [{ name: 'add-or-update', title: '编辑' }] },
  { title: '应用中心', name: 'application-center', components: [{ name: 'add-or-update', title: '编辑' }] },
  {
    title: '系统管理',
    name: 'system',
    pages: [
      { title: '租户管理', name: 'tenant', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '用户管理', name: 'user', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '公众端用户管理', name: 'public-end-user', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '公众端街道用户管理', name: 'public-end-street-user', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '角色管理', name: 'role', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '菜单管理', name: 'menu', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '部门管理', name: 'department', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '岗位管理', name: 'job', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '字典管理', name: 'dictionary', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '参数设置', name: 'parameter-settings', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '通知公告', name: 'notice-announcement', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '日志管理', name: 'log', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '街道子账户角色管理', name: 'street-sub-account-role', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '街道子账户账号管理', name: 'son-tenant-account', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '社区管理', name: 'community', components: [{ name: 'add-or-update', title: '编辑' }] },
    ],
  },
  {
    title: '系统监控',
    name: 'monitor',
    pages: [
      { title: '在线用户', name: 'online-users', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '定时任务', name: 'scheduled-tasks', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '数据监控', name: 'data-monitoring', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '服务监控', name: 'service-monitoring', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '缓存监控', name: 'cache-monitoring', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '缓存列表', name: 'cache-list', components: [{ name: 'add-or-update', title: '编辑' }] },
    ],
  },
  {
    title: '系统工具',
    name: 'tool',
    pages: [
      { title: '表单构建', name: 'form-construction', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '代码生成', name: 'code-generation', components: [{ name: 'add-or-update', title: '编辑' }] },
      { title: '系统接口', name: 'system-interface', components: [{ name: 'add-or-update', title: '编辑' }] },
    ],
  },
];
