export const locationRouters = [
  { icon: 'fa-home', title: '工作台', name: 'workbench' },
  { icon: 'fa-home', title: '应用后台', name: 'applicationTenant' },
  { icon: 'fa-home', title: 'Banner配置', name: 'banner' },
  { icon: 'fa-home', title: '快讯中心', name: 'news' },
  { icon: 'fa-home', title: '消息中心', name: 'message' },
  { icon: 'fa-home', title: '公告中心', name: 'announcement' },
  { icon: 'fa-home', title: '应用中心', name: 'applicationManage' },
  {
    icon: 'fa-home',
    title: '渣土车',
    name: 'slagCar',
    children: [
      { icon: 'fa-home', title: '事件管理', name: 'event' },
      { icon: 'fa-home', title: '巡查记录', name: 'inspection' },
      { icon: 'fa-home', title: '任务管理', name: 'task' },
      { icon: 'fa-home', title: '预警管理', name: 'alarm' },
      { icon: 'fa-home', title: '数据统计', name: 'slagCarstatistics' },
    ],
  },
  {
    icon: 'fa-home',
    title: '事件爆料',
    name: 'sjbl',
    children: [{ icon: 'fa-home', title: '事件管理', name: 'publicDisclosure' }],
  },
  {
    icon: 'fa-home',
    title: '无人机',
    name: 'uavManagement',
    children: [
      { icon: 'fa-home', title: '无人机预警', name: 'uavAlertEventList' },
      { icon: 'fa-home', title: '上报事件', name: 'uavReportEventList' },
      { icon: 'fa-home', title: '巡查记录', name: 'uavInspectionRecordList' },
      { icon: 'fa-home', title: '小区配置', name: 'uavCommunityPersonnelManagement' },
    ],
  },
  {
    icon: 'fa-home',
    title: '系统管理',
    name: 'system',
    children: [
      { icon: 'fa-home', title: '租户管理', name: 'tenant' },
      { icon: 'fa-home', title: '用户管理', name: 'user' },
      { icon: 'fa-home', title: '公众端用户管理', name: 'peoples' },
      { icon: 'fa-home', title: '公众端街道用户管理', name: 'orgPeoples' },
      { icon: 'fa-home', title: '角色管理', name: 'role' },
      { icon: 'fa-home', title: '菜单管理', name: 'menu' },
      { icon: 'fa-home', title: '部门管理', name: 'dept' },
      { icon: 'fa-home', title: '岗位管理', name: 'post' },
      { icon: 'fa-home', title: '字典管理', name: 'dict' },
      { icon: 'fa-home', title: '参数设置', name: 'config' },
      { icon: 'fa-home', title: '通知公告', name: 'notice' },
      { icon: 'fa-home', title: '日志管理', name: 'log' },
      { icon: 'fa-home', title: '街道子账户角色管理', name: 'sonTenantRoleManagement' },
      { icon: 'fa-home', title: '街道子账户账号管理', name: 'sonTenantAccountManagement' },
      { icon: 'fa-home', title: '社区管理', name: 'systemregionindex' },
    ],
  },
  {
    icon: 'fa-home',
    title: '系统监控',
    name: 'monitor',
    children: [
      { icon: 'fa-home', title: '在线用户', name: 'online' },
      { icon: 'fa-home', title: '定时任务', name: 'job' },
      { icon: 'fa-home', title: '数据监控', name: 'druid' },
      { icon: 'fa-home', title: '服务监控', name: 'server' },
      { icon: 'fa-home', title: '缓存监控', name: 'cache' },
      { icon: 'fa-home', title: '缓存列表', name: 'cacheList' },
    ],
  },
  {
    icon: 'fa-home',
    title: '系统工具',
    name: 'tool',
    children: [
      { icon: 'fa-home', title: '表单构建', name: 'build' },
      { icon: 'fa-home', title: '代码生成', name: 'gen' },
      { icon: 'fa-home', title: '系统接口', name: 'swagger' },
    ],
  },
];
